"""Byte storage for project references.

This is the security-sensitive half of uploads, so the rules are structural rather than
checked-by-convention:

* A storage location is **derived** from ``project_id`` and a generated reference id.
  Nothing in the path comes from the uploaded filename, so a filename cannot traverse,
  collide, or overwrite.
* The original filename is kept only as a DISPLAY name, sanitised, and never used to
  build a path.
* Every resolved path is re-checked for containment after symlink resolution, so a
  pre-existing symlink inside the project directory cannot redirect a write.
* Callers ask for bytes by id. No path ever crosses into a contract, a prompt, or the
  browser.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata
from pathlib import Path
from typing import Final, Optional

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_REFERENCE_ROOT: Final = REPO_ROOT / "runtime" / "references"

#: Conservative: a project id is used as a directory name.
PROJECT_ID_PATTERN: Final = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$")
#: Reference ids are generated by us, so they can be strict.
REFERENCE_ID_PATTERN: Final = re.compile(r"^[a-z0-9_]{3,64}$")

MAX_DISPLAY_NAME_LENGTH: Final = 120

#: Extensions permitted for the MVP, mapped to their canonical media type.
EXTENSION_MEDIA_TYPES: Final[dict[str, str]] = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".pdf": "application/pdf",
    ".txt": "text/plain",
    ".md": "text/markdown",
}


class ReferenceStorageError(ValueError):
    """Raised when a reference cannot be stored or read safely."""


def assert_safe_project_id(value: str) -> str:
    if not isinstance(value, str) or not PROJECT_ID_PATTERN.match(value):
        raise ReferenceStorageError(f"unsafe project id: {value!r}")
    return value


def assert_safe_reference_id(value: str) -> str:
    if not isinstance(value, str) or not REFERENCE_ID_PATTERN.match(value):
        raise ReferenceStorageError(f"unsafe reference id: {value!r}")
    return value


def sanitise_display_name(raw: str) -> str:
    """Make an uploaded filename safe to show. NOT used to build a path.

    Strips directory components, control characters and bidirectional overrides — the
    last of these because a right-to-left override can make ``photo\u202egnp.exe`` read
    as ``photo.png`` in a list.
    """
    if not isinstance(raw, str):
        return "reference"
    # Take the last component of either separator style, so "a/b\\c.png" -> "c.png".
    candidate = raw.replace("\\", "/").rsplit("/", 1)[-1]
    candidate = unicodedata.normalize("NFC", candidate)
    candidate = "".join(
        character
        for character in candidate
        if unicodedata.category(character)[0] != "C" and character not in "\u202a\u202b\u202c\u202d\u202e"
    )
    candidate = candidate.strip().strip(".")
    candidate = re.sub(r"\s+", " ", candidate)
    if not candidate:
        return "reference"
    return candidate[:MAX_DISPLAY_NAME_LENGTH]


def extension_of(display_name: str) -> str:
    suffix = Path(display_name).suffix.lower()
    return suffix if suffix in EXTENSION_MEDIA_TYPES else ""


def media_type_for(display_name: str) -> Optional[str]:
    return EXTENSION_MEDIA_TYPES.get(extension_of(display_name))


def checksum_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


class ReferenceFileStore:
    """Stores reference bytes under a platform-derived layout."""

    def __init__(self, root: Optional[Path] = None) -> None:
        self._root = Path(root) if root is not None else DEFAULT_REFERENCE_ROOT

    @property
    def root(self) -> Path:
        return self._root

    def project_directory(self, project_id: str) -> Path:
        assert_safe_project_id(project_id)
        return self._root / project_id

    def _resolved_path(self, project_id: str, stored_name: str) -> Path:
        directory = self.project_directory(project_id)
        # stored_name is generated by build_stored_name, never user input, but it is
        # re-validated here so a future caller cannot weaken the guarantee.
        if "/" in stored_name or "\\" in stored_name or stored_name in ("", ".", ".."):
            raise ReferenceStorageError(f"unsafe stored name: {stored_name!r}")
        candidate = directory / stored_name
        base = directory.resolve()
        resolved = candidate.resolve()
        if base != resolved and base not in resolved.parents:
            raise ReferenceStorageError("reference path escapes its project directory")
        return candidate

    @staticmethod
    def build_stored_name(reference_id: str, display_name: str) -> str:
        """A filename built from OUR identifier plus an allow-listed extension."""
        assert_safe_reference_id(reference_id)
        return f"{reference_id}{extension_of(display_name)}"

    def write(self, project_id: str, stored_name: str, data: bytes) -> Path:
        directory = self.project_directory(project_id)
        directory.mkdir(parents=True, exist_ok=True)
        target = self._resolved_path(project_id, stored_name)
        # Write to a temporary sibling then replace, so a reader never sees a partial file.
        temporary = target.with_name(target.name + ".partial")
        temporary.write_bytes(data)
        temporary.replace(target)
        return target

    def read(self, project_id: str, stored_name: str) -> Optional[bytes]:
        try:
            target = self._resolved_path(project_id, stored_name)
        except ReferenceStorageError:
            return None
        if not target.exists():
            return None
        return target.read_bytes()

    def path_for(self, project_id: str, stored_name: str) -> Optional[Path]:
        """The location of stored bytes, for internal use only.

        Used by the provider to attach image bytes to a model call. It is deliberately
        not part of any contract: nothing returns this to the browser.
        """
        try:
            target = self._resolved_path(project_id, stored_name)
        except ReferenceStorageError:
            return None
        return target if target.exists() else None

    def exists(self, project_id: str, stored_name: str) -> bool:
        return self.path_for(project_id, stored_name) is not None

    def delete(self, project_id: str, stored_name: str) -> bool:
        try:
            target = self._resolved_path(project_id, stored_name)
        except ReferenceStorageError:
            return False
        if not target.exists():
            return False
        target.unlink()
        return True
