"""GET /api/projects/{project_id}/artifacts/{artifact_id} — serve a preview.

Spec 001, Task 10.

    browser  --GET-->  this route  -->  ArtifactStore  -->  PNG bytes
                       ^^^^^^^^^^
                       project authorization + artifact lookup

This is the only way generated bytes leave the control plane, and it is
deliberately narrow.

WHAT IT CAN SERVE
-----------------
Registered artifacts, and nothing else. That is enforced by construction, not by
filtering:

  1. ``project_id`` is authorized through the trusted project registry FIRST. An
     unknown or path-shaped project is 404 and no lookup happens.
  2. ``artifact_id`` must satisfy the canonical artifact identifier pattern
     (a type prefix plus lowercase hex), so it is a single safe path segment and
     ``..``, separators, and absolute paths are unrepresentable.
  3. The filename is derived by the store from that id plus a fixed extension
     mapped from the media type. A caller never supplies a filename, so a
     ``.blend``, an execution journal record, a recovery snapshot, an ``.env``
     file, or a directory listing cannot be addressed.
  4. The store re-checks containment after symlink resolution.

Therefore there is no route that returns a directory listing, no route that takes a
path, and no way to reach a project file — only artifacts the worker registered.

PROJECT ISOLATION
-----------------
Identical to Task 9 job retrieval. An artifact belonging to a different project
returns exactly the same 404 as one that does not exist, so the response cannot be
used to probe for cross-project existence. There is no unscoped artifact route.

The checksum is reported in metadata for corruption detection and caching, and is
explicitly NOT an access credential: knowing it grants nothing.
"""

from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, Depends, Response

from studio_types import PreviewArtifact

from ..errors import error_body
from ..models import PreviewModel
from .support import AppDependencies, ControlPlaneHTTPError, get_dependencies

router = APIRouter(prefix="/api", tags=["artifacts"])

#: The one place the artifact path is built, so job responses and this route can
#: never disagree.
ARTIFACT_PATH_TEMPLATE = "/api/projects/{project_id}/artifacts/{artifact_id}"

#: Deliberately identical for "no such artifact" and "another project's artifact".
ARTIFACT_NOT_FOUND_MESSAGE = "no such artifact exists in this project"

PROJECT_NOT_FOUND_MESSAGE = "that project does not exist or is not available to you"

#: Previews are immutable: the artifact_id is derived from its content-producing
#: job, so a given id always denotes the same image. Safe to cache hard, and
#: private because artifacts are project-scoped and must not enter a shared cache.
CACHE_CONTROL = "private, max-age=31536000, immutable"


def artifact_path(project_id: str, artifact_id: str) -> str:
    """Build the project-scoped logical URL for an artifact."""
    return ARTIFACT_PATH_TEMPLATE.format(
        project_id=project_id, artifact_id=artifact_id
    )


def preview_model_for(
    project_id: str, artifact: PreviewArtifact
) -> PreviewModel:
    """Project a stored artifact into its HTTP view, adding the logical URL."""
    return PreviewModel(
        artifact_id=artifact.artifact_id,
        artifact_type=artifact.artifact_type,
        media_type=artifact.media_type,
        created_at=artifact.created_at,
        width=artifact.width,
        height=artifact.height,
        size_bytes=artifact.size_bytes,
        checksum=artifact.checksum,
        url=artifact_path(project_id, artifact.artifact_id),
        engine=artifact.engine,
    )


def preview_model_from_wire(
    project_id: str, wire: Optional[dict]
) -> Optional[PreviewModel]:
    """Project a worker-reported artifact document into its HTTP view.

    Returns None for anything that does not satisfy the canonical artifact shape,
    so a malformed report degrades to "no preview" rather than producing a broken
    URL.
    """
    if not isinstance(wire, dict) or not wire:
        return None
    from studio_preview.artifacts import artifact_from_wire

    try:
        artifact = artifact_from_wire(wire)
    except Exception:
        return None
    if artifact.project_id != project_id:
        # A worker must never hand the control plane an artifact attributed to a
        # different project.
        return None
    return preview_model_for(project_id, artifact)


@router.get(
    "/projects/{project_id}/artifacts/{artifact_id}",
    summary="Fetch a generated preview artifact",
    response_class=Response,
    responses={
        200: {
            "content": {"image/png": {}},
            "description": "The artifact bytes.",
        },
        404: {"description": "No such artifact in this project."},
    },
)
async def get_artifact(
    project_id: str,
    artifact_id: str,
    dependencies: AppDependencies = Depends(get_dependencies),
) -> Response:
    # ---- 1. authorize the project through the trusted boundary -------
    if dependencies.projects.get(project_id) is None:
        raise ControlPlaneHTTPError(
            status_code=404,
            body=error_body("VALIDATION_ERROR", PROJECT_NOT_FOUND_MESSAGE),
        )

    store = dependencies.artifacts
    if store is None:  # pragma: no cover - always configured by build_dependencies
        raise ControlPlaneHTTPError(
            status_code=404,
            body=error_body("VALIDATION_ERROR", ARTIFACT_NOT_FOUND_MESSAGE),
        )

    # ---- 2. project-scoped lookup ------------------------------------
    # An unsafe identifier is reported as "not found" like any other miss: the
    # reason is a server-side detail and must not become a probing oracle.
    artifact = store.get(project_id, artifact_id)
    data = store.read_bytes(project_id, artifact_id) if artifact else None
    if artifact is None or data is None:
        raise ControlPlaneHTTPError(
            status_code=404,
            body=error_body("VALIDATION_ERROR", ARTIFACT_NOT_FOUND_MESSAGE),
        )

    return Response(
        content=data,
        # Taken from the stored metadata, whose canonical pattern constrains it to
        # a well-formed media type, so it is safe in a header.
        media_type=artifact.media_type,
        headers={
            "Cache-Control": CACHE_CONTROL,
            "Content-Length": str(len(data)),
            # The checksum is exposed for corruption detection and caching. It is
            # not a credential.
            "ETag": f'"{artifact.checksum}"',
            # Previews are displayed, never downloaded as a named file, and no
            # filename is disclosed.
            "X-Content-Type-Options": "nosniff",
        },
    )


__all__ = [
    "ARTIFACT_NOT_FOUND_MESSAGE",
    "ARTIFACT_PATH_TEMPLATE",
    "CACHE_CONTROL",
    "PROJECT_NOT_FOUND_MESSAGE",
    "artifact_path",
    "preview_model_for",
    "preview_model_from_wire",
    "router",
]
